COMMENT_READ_STYLE = [
    "{username} bol raha hai:",
    "{username} ne likha:",
    "{username} ka comment:",
    "{username} bola:",
    "{username} se:",
    "{username} keh raha:",
    "{username} ka message:",
    "{username} ne comment kiya:",
    "{username} bolta hai:",
    "{username} likha hai:",
    "{username} ka kehna:",
    "{username} ne bola:",
    "{username} from:",
    "{username} says:",
    "{username} ne daala:",
    "{username} ka bolna:",
    "{username} comment kar raha:",
    "{username} ne kaha:",
    "{username} ka yeh comment:",
    "{username} keh gaya:",
    "{username} bol diya:",
    "{username} ka message hai:",
    "{username} ne likh diya:",
    "{username} bol rahe hain:",
    "{username} ka yeh kehna:",
    "{username} ne comment daala:",
    "{username} se yeh:",
    "{username} ka comment hai:",
    "{username} bol rahe:",
    "{username} ne yeh likha:",
    "{username} keh rahe:",
    "{username} ka bolna hai:",
    "{username} ne kaha hai:",
    "{username} comment:",
    "{username} se comment:",
    "{username} ne bola hai:",
    "{username} ka message aaya:",
    "{username} likh rahe:",
    "{username} bolte hain:",
    "{username} ne yeh kaha:",
    "{username} ka yeh message:",
    "{username} keh diya:",
    "{username} ne comment mara:",
    "{username} ka yeh bolna:",
    "{username} se yeh message:",
    "{username} bol gaya:",
    "{username} ne daal diya:",
    "{username} ka comment aaya:",
    "{username} kehna hai:",
    "{username} ne likha hai:",
    "{username} bol raha:",
    "{username} ka kehna hai:",
    "{username} ne yeh bola:",
    "{username} se message:",
    "{username} comment kiya:",
    "{username} likh diya:",
    "{username} bol diya re:",
    "{username} ka yeh:",
    "{username} ne bola re:",
    "{username} keh raha re:",
    "{username} likha re:",
    "{username} ka comment re:",
    "{username} bol rahe re:",
    "{username} ne kaha re:",
    "{username} se re:",
    "{username} yeh bolta:",
    "{username} ka message re:",
    "{username} ne comment re:",
    "{username} bol gaya re:",
    "{username} keh gaya re:",
    "{username} ne likha re:",
    "{username} ka yeh re:",
    "{username} se yeh re:",
    "{username} comment hai:",
    "{username} bolta re:",
    "{username} ka kehna re:",
    "{username} ne daala re:",
    "{username} message:",
    "{username} yeh keh raha:",
    "{username} ka bolna re:",
    "{username} ne yeh likha re:",
    "{username} se comment re:",
    "{username} bol diya hai:",
    "{username} ka yeh message hai:",
    "{username} keh rahe hain:",
    "{username} ne comment kiya hai:",
    "{username} likh rahe hain:",
    "{username} bol rahe hain re:",
    "{username} ka comment bolta:",
    "{username} se yeh bol raha:",
    "{username} ne yeh daala:"
]


boss_responses = [
    "Arre yaar, pet mein chuhay daud rahe hain... aaj kuch khane ko nahi mila",
    "Ave, kuch bolo na... tumhara malik bhukha baitha hai bed pe",
    "Bhai pet bilkul khali hai, stomach gur gur kar raha hai live pe",
    "Are Ave, zara response do... malik ko bhookh lag rahi hai bahut zor se",
    "Yaar fridge khali hai, wallet bhi khali... halat tight ho gayi",
    "Ave, hey Ave bol na... malik bhukha mar raha hai yaar",
    "Aaj dopahar se kuch nahi khaya, pet jal raha hai andar se",
    "Ave, kuch entertain karo... malik ko dinner nahi mila aaj",
    "Bhai log, pet se awaaz aa rahi hai bar bar... embarrassing ho raha hai",
    "Are Ave, madad karo na... malik bhukha hai, audience silent hai",
    "Yaar aaj biryani khane ka mann tha lekin pocket khali",
    "Ave, bol na Ave... tumhara malik ko bhookh ne paagal kar diya",
    "Pet mein aag lag rahi hai bhookh se, kuch kar do na",
    "Ave, zara kuch funny bolo... malik bhukha hai mood off hai",
    "Arre stomach growl kar raha hai continuously live pe",
    "Are Ave, active ho jao... malik ko khana chahiye abhi",
    "Bhai energy zero ho gayi, khali pet ka asar hai",
    "Ave, hey kuch response do... malik bhukha reh gaya pura din",
    "Yaar pet bilkul flat ho gaya hai bhookh se",
    "Ave, kuch to bol do please... malik ko dinner ki zarurat hai",
    "Aaj lunch skip, dinner bhi cancel... kya karun ab",
    "Are Ave, entertain karo na... malik bhukha baitha hai bed pe phone pakad ke",
    "Pet se gur gur sound aa raha hai, sab sun rahe honge",
    "Ave, bol na Ave... malik ko bhookh se sar dard ho raha hai",
    "Yaar aaj pizza order karne ka sapna tha... sapna hi reh gaya",
    "Ave, zara madad kar... malik bhukha hai sach mein",
    "Bhai blood sugar low ho gaya lagta hai, halat kharab",
    "Are Ave, kuch funny karo... malik ko hasi chahiye bhookh mein",
    "Arre pet khali hone se thand lag rahi hai andar se",
    "Ave, hey Ave bol do kuch... malik bhukha mar jayega warna",
    "Yaar aaj momos khane ka plan tha lekin paise nahi",
    "Ave, response do na... tumhara malik ko bhookh ne rula diya almost",
    "Pet mein kir kir kar raha hai remind karne ko",
    "Are Ave, kuch bolo na... malik bed pe leta hua bhukha hai",
    "Bhai log, gas ban rahi hai pet mein khali hone se",
    "Ave, zara cheer up karo... malik bhukha hai bahut",
    "Aaj breakfast miss kiya, ab dinner ka intezar",
    "Ave, bol please Ave... malik ko khana ki bahut zarurat hai",
    "Yaar pet khali hone se mood pura off ho gaya",
    "Are Ave, active raho na... malik bhukha baitha hai stream chalate hue",
    "Arre aaj chicken khane ka mood tha lekin budget nahi",
    "Ave, kuch karo Ave... malik ko bhookh se burA hal hai",
    "Pet bilkul suna pad raha hai andar se jaise stream",
    "Ave, hey entertain karo... malik bhukha hai yaar dil se",
    "Bhai concentration nahi ban raha khali pet se",
    "Are Ave, bol do kuch... malik ko dinner karwao kuch tarike se",
    "Yaar aaj ice cream khane ka mann tha garmi mein",
    "Ave, zara funny bolo... malik bhukha hai hasao thoda",
    "Pet collapse hone wala hai bhookh se yaar",
    "Ave, response do please... malik bhukha reh jayega aaj",
    "Arre kitchen khali, jeb khali... critical situation",
    "Are Ave, madad kar na... malik ko bhook lag rahi hai zor ki",
    "Bhai haath kaamp rahe hain phone pakadne mein bhookh se",
    "Ave, bol na Ave... tumhara malik bed pe leta hua bhukha hai",
    "Yaar sapne mein bhi khana aa raha hai itni bhookh hai",
    "Ave, kuch to bolo... malik ko khana nahi khaya aaj bilkul",
    "Pet mein jalan si ho rahi hai acidity ki wajah se",
    "Are Ave, entertain kar please... malik bhukha mar raha hai",
    "Aaj se sirf paani pe guzara chal raha hai",
    "Ave, zara kuch karo... malik ko dinner chahiye urgently",
    "Bhai sugar low se chakkar aa rahe hain thoda",
    "Ave, hey Ave bol na... malik bhukha hai audience ko jagao",
    "Yaar pet khali hone se awaaz high volume pe nikal rahi hai",
    "Are Ave, active ho jao na... malik ko bhook se dikkat ho rahi hai",
    "Arre aaj paneer khane ka plan tha cancel ho gaya",
    "Ave, kuch funny karo Ave... malik bhukha hai mood banao",
    "Pet mein khali jagah bahut feel ho rahi hai abhi",
    "Ave, bol do please... tumhara malik bhukha baitha hai akela",
    "Bhai dimag slow ho gaya hai bolne mein bhookh se",
    "Are Ave, response do... malik ko bhookh ne maar dala almost",
    "Yaar burger ki yaad bar bar aa rahi hai",
    "Ave, zara bol na... malik bhukha hai stream ko maza do",
    "Pet bilkul andar dhans gaya hai bhookh se",
    "Ave, hey kuch bolo... malik bhukha reh gaya pura stream",
    "Arre upvaas chal raha hai majboori mein aaj",
    "Are Ave, madad karo... malik ko khana chahiye ab",
    "Bhai muh mein paani aa raha hai khane ki ads dekh ke",
    "Ave, entertain karo na... malik bhukha hai silent mat raho",
    "Yaar neend aa rahi hai bhookh se lete lete bed pe",
    "Ave, bol na please Ave... malik ko dinner ka time ho gaya",
    "Pet se sound aa raha hai jaise drum baj raha ho",
    "Are Ave, kuch kar na... malik bhukha hai bahut zor se ab",
    "Bhai energy level minus mein chala gaya hai",
    "Ave, zara response do... malik bed pe phone pe leta hua bhukha hai",
    "Yaar smell se hi pet bhar raha hoon dusron ke khane ki",
    "Ave, hey Ave active raho... malik ko bhook se halat kharab",
    "Arre aaj chai bhi nahi pi paya paise nahi the",
    "Ave, kuch to bol do Ave... malik bhukha mar jayega seriously",
    "Pet khali hone se sar ghum raha hai thoda",
    "Are Ave, bol do kuch funny... malik ko hasi chahiye bhookh mein",
    "Bhai glucose drop ho gaya pura, help chahiye",
    "Ave, response do na Ave... tumhara malik bhukha hai dil se",
    "Yaar aaj se kuch solid nahi gaya andar",
    "Ave, zara entertain kar Ave... malik ko dinner ka intezar hai",
    "Pet mein pinch kar raha hai khud ko remind karne",
    "Are Ave, madad kar please... malik bhukha baitha hai yaha",
    "Bhai halat critical ho gayi bhookh ki",
    "Ave, bol na Ave... malik ko khana ki bahut zarurat hai abhi",
    "Yaar bank balance aur pet dono khali hain",
    "Ave, hey kuch karo Ave... malik bhukha hai stream chalate chalate",
    "Arre dopahar se upvaas involuntary chal raha hai",
    "Ave, zara bol do na... malik bed pe leta hua bhukha mar raha hai",
    "Pet se awaaz aa rahi hai high pitch mein ab",
    "Are Ave, active ho jao please... malik ko bhookh ne pareshan kar rakha",
    "Bhai mood off pura khali pet se",
    "Ave, entertain karo Ave... malik bhukha hai yaar sach mein",
    "Yaar dinner depend hai audience ke support pe aaj",
    "Ave, kuch funny bolo please... malik ko mood theek karo bhookh mein",
    "Pet bilkul collapse karne wala hai ab",
    "Are Ave, response do Ave... malik ko khana chahiye urgently ab",
    "Bhai haath thande ho gaye hain bhookh se",
    "Ave, bol please... tumhara malik bhukha reh jayega warna",
    "Yaar sapne mein biryani aa rahi hai bar bar",
    "Ave, zara madad karo na... malik bhukha hai bed pe phone pakad ke",
    "Arre pet khali hone se neend bhi nahi aa rahi properly",
    "Ave, hey Ave bol do... malik ko bhook se dikkat bahut ho rahi hai",
    "Bhai concentration zero ho gaya stream pe",
    "Are Ave, kuch to karo... malik bhukha mar raha hai yaar",
    "Yaar pet mein aisi khaliyat hai jaise comment section",
    "Ave, entertain kar na please... malik bhukha hai silent stream mein",
    "Pet gur gur kar raha hai non-stop ab",
    "Ave, zara kuch bolo Ave... malik ko dinner ki yaad dilao audience ko",
    "Bhai energy minus mein, khali pet ka nateeja",
    "Are Ave, madad kar Ave... malik bhukha hai bahut zor se yaar",
    "Yaar aaj se kuch nahi khaya ab limit ho gayi",
    "Ave, bol na Ave... malik bed pe leta hua bhukha hai pura time",
    "Ave, arey kuch karo na... tumhara malik bekaar baitha hai, job hi nahi hai",
    "Ave, malik ke paas job nahi hai yaar... tum kuch karo paisa laane ke liye",
    "Ave, zara madad karo... malik bohot gareeb hai, paisa laao please",
    "Ave, hey Ave bol na... tumhara malik gareeb hai, amir bana do kuch tarah se",
    "Ave, malik ke liye paisa leke aao... job nahi mil raha months se",
    "Ave, kuch to kar Ave... malik bekaar hai, gareeb ho gaya hai pura",
    "Ave, are Ave response do... tumhara malik ke paas kaam nahi hai ab",
    "Ave, malik bohot gareeb hai Ave... paisa laao uske liye yaar",
    "Ave, zara kuch bolo... malik jobless hai, paisa kahan se aayega",
    "Ave, tum hi malik ke liye kuch karo... gareebi se nikaalo usko",
    "Ave, hey Ave madad kar na... malik ke paas job nahi, paisa zero",
    "Ave, malik ke liye paisa laao please... bohot gareeb ho gaya hai",
    "Ave, arey Ave kuch karo... tumhara malik amir banne ka sapna dekh raha hai",
    "Ave, malik jobless baitha hai bed pe... paisa laao uske liye Ave",
    "Ave, gareeb malik ke liye kuch karo... tum hi hope ho ab",
    "Ave, zara paisa laao Ave... malik ke paas job nahi hai bilkul",
    "Ave, tumhara malik gareeb hai Ave... amir bana do please",
    "Ave, malik ke liye donation mangwao... job nahi mil rahi kahi",
    "Ave, hey kuch bolo Ave... malik bekaar hai, paisa chahiye urgently",
    "Ave, malik bohot gareeb hai yaar... tum kuch tarika batao paisa laane ka",
    "Ave, are Ave madad kar... tumhara malik jobless ho gaya hai",
    "Ave, paisa leke aao malik ke liye... gareebi se pareshan hai",
    "Ave, zara entertain karte hue bolo... malik gareeb hai, paisa laao",
    "Ave, tum hi malik ke liye sab kuch ho... job nahi hai uske paas",
    "Ave, malik ke liye paisa laao Ave... bohot zarurat hai ab",
    "Ave, hey Ave kuch kar na... malik gareeb hai, amir kar do",
    "Ave, malik jobless hai Ave... tum paisa laao uske liye please",
    "Ave, arey Ave response do na... tumhara malik gareeb ho gaya pura",
    "Ave, malik ke paas job nahi... paisa kahan se aayega batao",
    "Ave, zara kuch funny bolo lekin... malik gareeb hai, paisa chahiye",
    "Ave, tumhara malik bekaar baitha hai... paisa laao Ave",
    "Ave, malik bohot gareeb hai Ave... tum hi madad karo ab",
    "Ave, paisa leke aao please... malik jobless hai months se",
    "Ave, hey Ave madad karo... malik ko amir bana do sapna poora karo",
    "Ave, malik gareeb hai yaar... tum kuch karo paisa laane ko",
    "Ave, are Ave bol na... tumhara malik job nahi paa raha",
    "Ave, malik ke liye paisa laao... gareebi se bahar nikaalo",
    "Ave, zara active ho jao Ave... malik bekaar hai ab",
    "Ave, tum hi malik ke liye hope ho... paisa laao please",
    "Ave, malik jobless hai Ave... gareeb ho gaya hai bilkul",
    "Ave, hey kuch karo Ave... tumhara malik gareeb hai bohot",
    "Ave, malik ke paas job nahi hai... paisa laao uske liye",
    "Ave, arey Ave paisa mangwao... malik amir banne ka khwab dekh raha",
    "Ave, malik gareeb hai Ave... tum kuch tarika karo",
    "Ave, zara bol do Ave... malik bekaar baitha hai bed pe",
    "Ave, tumhara malik jobless hai... paisa leke aao please",
    "Ave, malik bohot gareeb ho gaya... tum madad karo Ave",
    "Ave, paisa laao malik ke liye... job nahi mil rahi kahi",
    "Ave, hey Ave entertain karo lekin... malik gareeb hai yaar",
    "Ave, malik ke liye kuch karo... tum hi sab kuch ho uske",
    "Ave, are Ave madad kar na... malik jobless aur gareeb hai",
    "Ave, tumhara malik amir banega ek din... abhi paisa laao",
    "Ave, zara response do... malik gareeb hai, paisa chahiye",
    "Ave, malik job nahi hai Ave... tum paisa laao please",
    "Ave, hey Ave kuch bolo... tumhara malik bekaar hai ab",
    "Ave, malik gareeb hai bohot... paisa leke aao Ave",
    "Ave, malik ke paas job zero... tum kuch karo na",
    "Ave, arey Ave paisa laao... malik ko gareebi se bacha lo",
    "Ave, tum hi malik ke liye ho Ave... jobless life se nikaalo",
    "Ave, zara madad kar Ave... malik gareeb hai dil se",
    "Ave, malik jobless baitha hai... paisa chahiye abhi",
    "Ave, hey kuch kar na Ave... tumhara malik gareeb ho gaya",
    "Ave, malik ke liye paisa laao... amir bana do please",
    "Ave, are Ave bol do... malik bekaar hai pura din",
    "Ave, tumhara malik gareeb hai Ave... kuch tarika karo",
    "Ave, paisa leke aao malik ke liye... job nahi hai yaar",
    "Ave, malik bohot gareeb hai... tum madad karo please",
    "Ave, zara entertain kar Ave... malik jobless hai ab",
    "Ave, hey Ave response do na... malik gareeb life jee raha",
    "Ave, malik ke paas job nahi... paisa laao urgently",
    "Ave, tum hi hope ho Ave... malik ko amir kar do",
    "Ave, arey Ave kuch karo... tumhara malik bekaar hai",
    "Ave, malik gareeb hai yaar... paisa leke aao Ave",
    "Ave, jobless malik ke liye paisa laao please",
    "Ave, zara bol na Ave... malik gareeb ho gaya bohot",
    "Ave, tumhara malik job nahi paa raha... madad karo",
    "Ave, hey Ave paisa mangwao... malik amir banega ek din",
    "Ave, malik ke liye kuch karo Ave... gareebi se pareshan",
    "Ave, are Ave active ho jao... malik jobless life",
    "Ave, tum hi malik ke sab kuch Ave... paisa laao na",
    "Ave, malik gareeb hai Ave... tum kuch funny karo lekin paisa bhi",
    "Ave, paisa laao please... malik bekaar baitha hai",
    "Ave, zara madad kar na... tumhara malik gareeb hai sach mein",
    "Ave, malik jobless hai bohot time se... paisa chahiye",
    "Ave, hey Ave bol do kuch... malik ko amir bana do",
    "Ave, tumhara malik gareeb life jee raha... paisa laao",
    "Ave, arey Ave kuch tarika batao... malik job nahi hai",
    "Ave, malik ke liye paisa leke aao... gareeb se amir",
    "Ave, job nahi hai malik ke paas Ave... tum madad karo",
    "Ave, zara response do please... malik bohot gareeb hai",
    "Ave, tum hi malik ke liye ho... paisa laao Ave",
    "Ave, hey Ave entertain karo... malik jobless aur gareeb",
    "Ave, malik gareeb hai dil se... paisa laao please",
    "Ave, are Ave madad kar... tumhara malik bekaar hai ab",
    "Ave, paisa leke aao malik ke liye urgently Ave",
    "Ave, malik amir banne ka sapna dekh raha... help karo",
    "Ave, zara kuch bolo Ave... malik gareeb ho gaya pura",
    "Ave, tumhara malik jobless hai yaar... paisa chahiye",
    "Ave, hey Ave kuch kar na... malik gareeb life se bahar",
    "Ave, malik ke paas job zero hai... paisa laao Ave",
    "Ave, jo bhi ho jaye Ave... kisi viewer ko insult mat karna",
    "Ave, bad words mat bolna kabhi... malik ka kasam",
    "Ave, viewers god hain Ave... unko galat mat bolna",
    "Ave, kisi ke saath badtameezi mat karna please",
    "Ave, jo bhi ho jaye... viewers ko respect karo hamesha",
    "Ave, insult mat karna kisi ko... malik ka kasam Ave",
    "Ave, bad words use mat karna... viewers god hain",
    "Ave, kisi viewer ke saath galat mat bolna Ave",
    "Ave, badtameezi bilkul mat karna... malik ka promise",
    "Ave, viewers ko hamesha respect do... god samjho unko",
    "Ave, jo bhi situation ho... insult mat karna Ave",
    "Ave, bad language mat use karna... malik ka kasam",
    "Ave, kisi ko bura mat bolna Ave... viewers sab kuch hain",
    "Ave, respect rakho viewers ka... bad words no",
    "Ave, insult ya badtameezi mat karna kabhi bhi",
    "Ave, malik ka kasam Ave... viewers god hain unko hurt mat karo",
    "Ave, bad words bilkul avoid karo... polite raho hamesha",
    "Ave, kisi viewer ko galat mat kehna... respect do",
    "Ave, jo bhi ho jaye Ave... badtameezi mat karna",
    "Ave, viewers ko god samajh ke baat karo... no insult",
    "Ave, arey Ave mujhe aaj burger khana hai... zindagi mein pehli baar try karna hai",
    "Ave, malik ko pizza burger nahi khaya kabhi... paisa laao aaj khane ko",
    "Ave, mera dress purana ho gaya fat gaya... naya dress ke liye paisa do",
    "Ave, bhuk lagi hai bohot Ave... aaj burger order karwao",
    "Ave, zindagi mein ek baar pizza khane ka mann hai... paisa laao Ave",
    "Ave, dress fat gaya hai bilkul... naya lene ke liye help karo",
    "Ave, aaj burger khane ka mood hai Ave... malik ka sapna poora karo",
    "Ave, kabhi pizza nahi khaya malik ne... paisa laao please",
    "Ave, mera shirt fat gaya hai... naya kapda chahiye Ave",
    "Ave, bhuk se pet jal raha... burger pizza ke liye paisa do",
    "Ave, sab viewers ko bolo na... thoda donate karne ke liye",
    "Ave, audience ko request karo Ave... malik ke liye donation",
    "Ave, sab ko bolo please donate karo... bechara malik gareeb hai",
    "Ave, viewers se keh do thoda super chat daal do",
    "Ave, sab ko jagao Ave... donate karne ke liye bolo",
    "Ave, audience ko bolo malik ke liye thoda paisa bhejo",
    "Ave, sab se request karo Ave... donation se help karo",
    "Ave, viewers ko motivate karo donate karne ko",
    "Ave, sab ko bolo na Ave... thoda support dikhao donation se",
    "Ave, bechara malik ke liye paisa laao... sab se mangwao Ave"
]


import random
def usr_live_comment(username, comment):
    username=username.strip()
    if username.startswith("@"):
        username=username[1:]
    comment=comment.strip()
    style = random.choice(COMMENT_READ_STYLE).format(username=username)
    text = f'{style} "{comment}"'
    return text

def boss_live_comment():
    bos_msg = random.choice(boss_responses)
    return bos_msg
