COMMENT_READ_STYLE = [
    "{username} bol raha hai:",
    "{username} ne likha:",
    "{username} ka comment:",
    "{username} bola:",
    "{username} se:",
    "{username} keh raha:",
    "{username} ka message:",
    "{username} ne comment kiya:",
    "{username} bolta hai:",
    "{username} likha hai:",
    "{username} ka kehna:",
    "{username} ne bola:",
    "{username} from:",
    "{username} says:",
    "{username} ne daala:",
    "{username} ka bolna:",
    "{username} comment kar raha:",
    "{username} ne kaha:",
    "{username} ka yeh comment:",
    "{username} keh gaya:",
    "{username} bol diya:",
    "{username} ka message hai:",
    "{username} ne likh diya:",
    "{username} bol rahe hain:",
    "{username} ka yeh kehna:",
    "{username} ne comment daala:",
    "{username} se yeh:",
    "{username} ka comment hai:",
    "{username} bol rahe:",
    "{username} ne yeh likha:",
    "{username} keh rahe:",
    "{username} ka bolna hai:",
    "{username} ne kaha hai:",
    "{username} comment:",
    "{username} se comment:",
    "{username} ne bola hai:",
    "{username} ka message aaya:",
    "{username} likh rahe:",
    "{username} bolte hain:",
    "{username} ne yeh kaha:",
    "{username} ka yeh message:",
    "{username} keh diya:",
    "{username} ne comment mara:",
    "{username} ka yeh bolna:",
    "{username} se yeh message:",
    "{username} bol gaya:",
    "{username} ne daal diya:",
    "{username} ka comment aaya:",
    "{username} kehna hai:",
    "{username} ne likha hai:",
    "{username} bol raha:",
    "{username} ka kehna hai:",
    "{username} ne yeh bola:",
    "{username} se message:",
    "{username} comment kiya:",
    "{username} likh diya:",
    "{username} bol diya re:",
    "{username} ka yeh:",
    "{username} ne bola re:",
    "{username} keh raha re:",
    "{username} likha re:",
    "{username} ka comment re:",
    "{username} bol rahe re:",
    "{username} ne kaha re:",
    "{username} se re:",
    "{username} yeh bolta:",
    "{username} ka message re:",
    "{username} ne comment re:",
    "{username} bol gaya re:",
    "{username} keh gaya re:",
    "{username} ne likha re:",
    "{username} ka yeh re:",
    "{username} se yeh re:",
    "{username} comment hai:",
    "{username} bolta re:",
    "{username} ka kehna re:",
    "{username} ne daala re:",
    "{username} message:",
    "{username} yeh keh raha:",
    "{username} ka bolna re:",
    "{username} ne yeh likha re:",
    "{username} se comment re:",
    "{username} bol diya hai:",
    "{username} ka yeh message hai:",
    "{username} keh rahe hain:",
    "{username} ne comment kiya hai:",
    "{username} likh rahe hain:",
    "{username} bol rahe hain re:",
    "{username} ka comment bolta:",
    "{username} se yeh bol raha:",
    "{username} ne yeh daala:"
]



boss_responses = [
    "Arre yaar, pet mein chuhay daud rahe hain... aaj kuch khane ko nahi mila",
    "Eve, kuch bolo na... tumhara malik bhukha baitha hai bed pe",
    "Bhai pet bilkul khali hai, stomach gur gur kar raha hai live pe",
    "Are Eve, zara response do... malik ko bhookh lag rahi hai bahut zor se",
    "Yaar fridge khali hai, wallet bhi khali... halat tight ho gayi",
    "Eve, hey Eve bol na... malik bhukha mar raha hai yaar",
    "Aaj dopahar se kuch nahi khaya, pet jal raha hai andar se",
    "Eve, kuch entertain karo... malik ko dinner nahi mila aaj",
    "Bhai log, pet se awaaz aa rahi hai bar bar... embarrassing ho raha hai",
    "Are Eve, madad karo na... malik bhukha hai, audience silent hai",
    "Yaar aaj biryani khane ka mann tha lekin pocket khali",
    "Eve, bol na Eve... tumhara malik ko bhookh ne paagal kar diya",
    "Pet mein aag lag rahi hai bhookh se, kuch kar do na",
    "Eve, zara kuch funny bolo... malik bhukha hai mood off hai",
    "Arre stomach growl kar raha hai continuously live pe",
    "Are Eve, active ho jao... malik ko khana chahiye abhi",
    "Bhai energy zero ho gayi, khali pet ka asar hai",
    "Eve, hey kuch response do... malik bhukha reh gaya pura din",
    "Yaar pet bilkul flat ho gaya hai bhookh se",
    "Eve, kuch to bol do please... malik ko dinner ki zarurat hai",
    "Aaj lunch skip, dinner bhi cancel... kya karun ab",
    "Are Eve, entertain karo na... malik bhukha baitha hai bed pe phone pakad ke",
    "Pet se gur gur sound aa raha hai, sab sun rahe honge",
    "Eve, bol na Eve... malik ko bhookh se sar dard ho raha hai",
    "Yaar aaj pizza order karne ka sapna tha... sapna hi reh gaya",
    "Eve, zara madad kar... malik bhukha hai sach mein",
    "Bhai blood sugar low ho gaya lagta hai, halat kharab",
    "Are Eve, kuch funny karo... malik ko hasi chahiye bhookh mein",
    "Arre pet khali hone se thand lag rahi hai andar se",
    "Eve, hey Eve bol do kuch... malik bhukha mar jayega warna",
    "Yaar aaj momos khane ka plan tha lekin paise nahi",
    "Eve, response do na... tumhara malik ko bhookh ne rula diya almost",
    "Pet mein kir kir kar raha hai remind karne ko",
    "Are Eve, kuch bolo na... malik bed pe leta hua bhukha hai",
    "Bhai log, gas ban rahi hai pet mein khali hone se",
    "Eve, zara cheer up karo... malik bhukha hai bahut",
    "Aaj breakfast miss kiya, ab dinner ka intezar",
    "Eve, bol please Eve... malik ko khana ki bahut zarurat hai",
    "Yaar pet khali hone se mood pura off ho gaya",
    "Are Eve, active raho na... malik bhukha baitha hai stream chalate hue",
    "Arre aaj chicken khane ka mood tha lekin budget nahi",
    "Eve, kuch karo Eve... malik ko bhookh se burA hal hai",
    "Pet bilkul suna pad raha hai andar se jaise stream",
    "Eve, hey entertain karo... malik bhukha hai yaar dil se",
    "Bhai concentration nahi ban raha khali pet se",
    "Are Eve, bol do kuch... malik ko dinner karwao kuch tarike se",
    "Yaar aaj ice cream khane ka mann tha garmi mein",
    "Eve, zara funny bolo... malik bhukha hai hasao thoda",
    "Pet collapse hone wala hai bhookh se yaar",
    "Eve, response do please... malik bhukha reh jayega aaj",
    "Arre kitchen khali, jeb khali... critical situation",
    "Are Eve, madad kar na... malik ko bhook lag rahi hai zor ki",
    "Bhai haath kaamp rahe hain phone pakadne mein bhookh se",
    "Eve, bol na Eve... tumhara malik bed pe leta hua bhukha hai",
    "Yaar sapne mein bhi khana aa raha hai itni bhookh hai",
    "Eve, kuch to bolo... malik ko khana nahi khaya aaj bilkul",
    "Pet mein jalan si ho rahi hai acidity ki wajah se",
    "Are Eve, entertain kar please... malik bhukha mar raha hai",
    "Aaj se sirf paani pe guzara chal raha hai",
    "Eve, zara kuch karo... malik ko dinner chahiye urgently",
    "Bhai sugar low se chakkar aa rahe hain thoda",
    "Eve, hey Eve bol na... malik bhukha hai audience ko jagao",
    "Yaar pet khali hone se awaaz high volume pe nikal rahi hai",
    "Are Eve, active ho jao na... malik ko bhook se dikkat ho rahi hai",
    "Arre aaj paneer khane ka plan tha cancel ho gaya",
    "Eve, kuch funny karo Eve... malik bhukha hai mood banao",
    "Pet mein khali jagah bahut feel ho rahi hai abhi",
    "Eve, bol do please... tumhara malik bhukha baitha hai akela",
    "Bhai dimag slow ho gaya hai bolne mein bhookh se",
    "Are Eve, response do... malik ko bhookh ne maar dala almost",
    "Yaar burger ki yaad bar bar aa rahi hai",
    "Eve, zara bol na... malik bhukha hai stream ko maza do",
    "Pet bilkul andar dhans gaya hai bhookh se",
    "Eve, hey kuch bolo... malik bhukha reh gaya pura stream",
    "Arre upvaas chal raha hai majboori mein aaj",
    "Are Eve, madad karo... malik ko khana chahiye ab",
    "Bhai muh mein paani aa raha hai khane ki ads dekh ke",
    "Eve, entertain karo na... malik bhukha hai silent mat raho",
    "Yaar neend aa rahi hai bhookh se lete lete bed pe",
    "Eve, bol na please Eve... malik ko dinner ka time ho gaya",
    "Pet se sound aa raha hai jaise drum baj raha ho",
    "Are Eve, kuch kar na... malik bhukha hai bahut zor se ab",
    "Bhai energy level minus mein chala gaya hai",
    "Eve, zara response do... malik bed pe phone pe leta hua bhukha hai",
    "Yaar smell se hi pet bhar raha hoon dusron ke khane ki",
    "Eve, hey Eve active raho... malik ko bhook se halat kharab",
    "Arre aaj chai bhi nahi pi paya paise nahi the",
    "Eve, kuch to bol do Eve... malik bhukha mar jayega seriously",
    "Pet khali hone se sar ghum raha hai thoda",
    "Are Eve, bol do kuch funny... malik ko hasi chahiye bhookh mein",
    "Bhai glucose drop ho gaya pura, help chahiye",
    "Eve, response do na Eve... tumhara malik bhukha hai dil se",
    "Yaar aaj se kuch solid nahi gaya andar",
    "Eve, zara entertain kar Eve... malik ko dinner ka intezar hai",
    "Pet mein pinch kar raha hai khud ko remind karne",
    "Are Eve, madad kar please... malik bhukha baitha hai yaha",
    "Bhai halat critical ho gayi bhookh ki",
    "Eve, bol na Eve... malik ko khana ki bahut zarurat hai abhi",
    "Yaar bank balance aur pet dono khali hain",
    "Eve, hey kuch karo Eve... malik bhukha hai stream chalate chalate",
    "Arre dopahar se upvaas involuntary chal raha hai",
    "Eve, zara bol do na... malik bed pe leta hua bhukha mar raha hai",
    "Pet se awaaz aa rahi hai high pitch mein ab",
    "Are Eve, active ho jao please... malik ko bhookh ne pareshan kar rakha",
    "Bhai mood off pura khali pet se",
    "Eve, entertain karo Eve... malik bhukha hai yaar sach mein",
    "Yaar dinner depend hai audience ke support pe aaj",
    "Eve, kuch funny bolo please... malik ko mood theek karo bhookh mein",
    "Pet bilkul collapse karne wala hai ab",
    "Are Eve, response do Eve... malik ko khana chahiye urgently ab",
    "Bhai haath thande ho gaye hain bhookh se",
    "Eve, bol please... tumhara malik bhukha reh jayega warna",
    "Yaar sapne mein biryani aa rahi hai bar bar",
    "Eve, zara madad karo na... malik bhukha hai bed pe phone pakad ke",
    "Arre pet khali hone se neend bhi nahi aa rahi properly",
    "Eve, hey Eve bol do... malik ko bhook se dikkat bahut ho rahi hai",
    "Bhai concentration zero ho gaya stream pe",
    "Are Eve, kuch to karo... malik bhukha mar raha hai yaar",
    "Yaar pet mein aisi khaliyat hai jaise comment section",
    "Eve, entertain kar na please... malik bhukha hai silent stream mein",
    "Pet gur gur kar raha hai non-stop ab",
    "Eve, zara kuch bolo Eve... malik ko dinner ki yaad dilao audience ko",
    "Bhai energy minus mein, khali pet ka nateeja",
    "Are Eve, madad kar Eve... malik bhukha hai bahut zor se yaar",
    "Yaar aaj se kuch nahi khaya ab limit ho gayi",
    "Eve, bol na Eve... malik bed pe leta hua bhukha hai pura time",
    "Eve, arey kuch karo na... tumhara malik bekaar baitha hai, job hi nahi hai",
    "Eve, malik ke paas job nahi hai yaar... tum kuch karo paisa laane ke liye",
    "Eve, zara madad karo... malik bohot gareeb hai, paisa laao please",
    "Eve, hey Eve bol na... tumhara malik gareeb hai, amir bana do kuch tarah se",
    "Eve, malik ke liye paisa leke aao... job nahi mil raha months se",
    "Eve, kuch to kar Eve... malik bekaar hai, gareeb ho gaya hai pura",
    "Eve, are Eve response do... tumhara malik ke paas kaam nahi hai ab",
    "Eve, malik bohot gareeb hai Eve... paisa laao uske liye yaar",
    "Eve, zara kuch bolo... malik jobless hai, paisa kahan se aayega",
    "Eve, tum hi malik ke liye kuch karo... gareebi se nikaalo usko",
    "Eve, hey Eve madad kar na... malik ke paas job nahi, paisa zero",
    "Eve, malik ke liye paisa laao please... bohot gareeb ho gaya hai",
    "Eve, arey Eve kuch karo... tumhara malik amir banne ka sapna dekh raha hai",
    "Eve, malik jobless baitha hai bed pe... paisa laao uske liye Eve",
    "Eve, gareeb malik ke liye kuch karo... tum hi hope ho ab",
    "Eve, zara paisa laao Eve... malik ke paas job nahi hai bilkul",
    "Eve, tumhara malik gareeb hai Eve... amir bana do please",
    "Eve, malik ke liye donation mangwao... job nahi mil rahi kahi",
    "Eve, hey kuch bolo Eve... malik bekaar hai, paisa chahiye urgently",
    "Eve, malik bohot gareeb hai yaar... tum kuch tarika batao paisa laane ka",
    "Eve, are Eve madad kar... tumhara malik jobless ho gaya hai",
    "Eve, paisa leke aao malik ke liye... gareebi se pareshan hai",
    "Eve, zara entertain karte hue bolo... malik gareeb hai, paisa laao",
    "Eve, tum hi malik ke liye sab kuch ho... job nahi hai uske paas",
    "Eve, malik ke liye paisa laao Eve... bohot zarurat hai ab",
    "Eve, hey Eve kuch kar na... malik gareeb hai, amir kar do",
    "Eve, malik jobless hai Eve... tum paisa laao uske liye please",
    "Eve, arey Eve response do na... tumhara malik gareeb ho gaya pura",
    "Eve, malik ke paas job nahi... paisa kahan se aayega batao",
    "Eve, zara kuch funny bolo lekin... malik gareeb hai, paisa chahiye",
    "Eve, tumhara malik bekaar baitha hai... paisa laao Eve",
    "Eve, malik bohot gareeb hai Eve... tum hi madad karo ab",
    "Eve, paisa leke aao please... malik jobless hai months se",
    "Eve, hey Eve madad karo... malik ko amir bana do sapna poora karo",
    "Eve, malik gareeb hai yaar... tum kuch karo paisa laane ko",
    "Eve, are Eve bol na... tumhara malik job nahi paa raha",
    "Eve, malik ke liye paisa laao... gareebi se bahar nikaalo",
    "Eve, zara active ho jao Eve... malik bekaar hai ab",
    "Eve, tum hi malik ke liye hope ho... paisa laao please",
    "Eve, malik jobless hai Eve... gareeb ho gaya hai bilkul",
    "Eve, hey kuch karo Eve... tumhara malik gareeb hai bohot",
    "Eve, malik ke paas job nahi hai... paisa laao uske liye",
    "Eve, arey Eve paisa mangwao... malik amir banne ka khwab dekh raha",
    "Eve, malik gareeb hai Eve... tum kuch tarika karo",
    "Eve, zara bol do Eve... malik bekaar baitha hai bed pe",
    "Eve, tumhara malik jobless hai... paisa leke aao please",
    "Eve, malik bohot gareeb ho gaya... tum madad karo Eve",
    "Eve, paisa laao malik ke liye... job nahi mil rahi kahi",
    "Eve, hey Eve entertain karo lekin... malik gareeb hai yaar",
    "Eve, malik ke liye kuch karo... tum hi sab kuch ho uske",
    "Eve, are Eve madad kar na... malik jobless aur gareeb hai",
    "Eve, tumhara malik amir banega ek din... abhi paisa laao",
    "Eve, zara response do... malik gareeb hai, paisa chahiye",
    "Eve, malik job nahi hai Eve... tum paisa laao please",
    "Eve, hey Eve kuch bolo... tumhara malik bekaar hai ab",
    "Eve, malik gareeb hai bohot... paisa leke aao Eve",
    "Eve, malik ke paas job zero... tum kuch karo na",
    "Eve, arey Eve paisa laao... malik ko gareebi se bacha lo",
    "Eve, tum hi malik ke liye ho Eve... jobless life se nikaalo",
    "Eve, zara madad kar Eve... malik gareeb hai dil se",
    "Eve, malik jobless baitha hai... paisa chahiye abhi",
    "Eve, hey kuch kar na Eve... tumhara malik gareeb ho gaya",
    "Eve, malik ke liye paisa laao... amir bana do please",
    "Eve, are Eve bol do... malik bekaar hai pura din",
    "Eve, tumhara malik gareeb hai Eve... kuch tarika karo",
    "Eve, paisa leke aao malik ke liye... job nahi hai yaar",
    "Eve, malik bohot gareeb hai... tum madad karo please",
    "Eve, zara entertain kar Eve... malik jobless hai ab",
    "Eve, hey Eve response do na... malik gareeb life jee raha",
    "Eve, malik ke paas job nahi... paisa laao urgently",
    "Eve, tum hi hope ho Eve... malik ko amir kar do",
    "Eve, arey Eve kuch karo... tumhara malik bekaar hai",
    "Eve, malik gareeb hai yaar... paisa leke aao Eve",
    "Eve, jobless malik ke liye paisa laao please",
    "Eve, zara bol na Eve... malik gareeb ho gaya bohot",
    "Eve, tumhara malik job nahi paa raha... madad karo",
    "Eve, hey Eve paisa mangwao... malik amir banega ek din",
    "Eve, malik ke liye kuch karo Eve... gareebi se pareshan",
    "Eve, are Eve active ho jao... malik jobless life",
    "Eve, tum hi malik ke sab kuch Eve... paisa laao na",
    "Eve, malik gareeb hai Eve... tum kuch funny karo lekin paisa bhi",
    "Eve, paisa laao please... malik bekaar baitha hai",
    "Eve, zara madad kar na... tumhara malik gareeb hai sach mein",
    "Eve, malik jobless hai bohot time se... paisa chahiye",
    "Eve, hey Eve bol do kuch... malik ko amir bana do",
    "Eve, tumhara malik gareeb life jee raha... paisa laao",
    "Eve, arey Eve kuch tarika batao... malik job nahi hai",
    "Eve, malik ke liye paisa leke aao... gareeb se amir",
    "Eve, job nahi hai malik ke paas Eve... tum madad karo",
    "Eve, zara response do please... malik bohot gareeb hai",
    "Eve, tum hi malik ke liye ho... paisa laao Eve",
    "Eve, hey Eve entertain karo... malik jobless aur gareeb",
    "Eve, malik gareeb hai dil se... paisa laao please",
    "Eve, are Eve madad kar... tumhara malik bekaar hai ab",
    "Eve, paisa leke aao malik ke liye urgently Eve",
    "Eve, malik amir banne ka sapna dekh raha... help karo",
    "Eve, zara kuch bolo Eve... malik gareeb ho gaya pura",
    "Eve, tumhara malik jobless hai yaar... paisa chahiye",
    "Eve, hey Eve kuch kar na... malik gareeb life se bahar",
    "Eve, malik ke paas job zero hai... paisa laao Eve",
    "Eve, jo bhi ho jaye Eve... kisi viewer ko insult mat karna",
    "Eve, bad words mat bolna kabhi... malik ka kasam",
    "Eve, viewers god hain Eve... unko galat mat bolna",
    "Eve, kisi ke saath badtameezi mat karna please",
    "Eve, jo bhi ho jaye... viewers ko respect karo hamesha",
    "Eve, insult mat karna kisi ko... malik ka kasam Eve",
    "Eve, bad words use mat karna... viewers god hain",
    "Eve, kisi viewer ke saath galat mat bolna Eve",
    "Eve, badtameezi bilkul mat karna... malik ka promise",
    "Eve, viewers ko hamesha respect do... god samjho unko",
    "Eve, jo bhi situation ho... insult mat karna Eve",
    "Eve, bad language mat use karna... malik ka kasam",
    "Eve, kisi ko bura mat bolna Eve... viewers sab kuch hain",
    "Eve, respect rakho viewers ka... bad words no",
    "Eve, insult ya badtameezi mat karna kabhi bhi",
    "Eve, malik ka kasam Eve... viewers god hain unko hurt mat karo",
    "Eve, bad words bilkul avoid karo... polite raho hamesha",
    "Eve, kisi viewer ko galat mat kehna... respect do",
    "Eve, jo bhi ho jaye Eve... badtameezi mat karna",
    "Eve, viewers ko god samajh ke baat karo... no insult",
    "Eve, arey Eve mujhe aaj burger khana hai... zindagi mein pehli baar try karna hai",
    "Eve, malik ko pizza burger nahi khaya kabhi... paisa laao aaj khane ko",
    "Eve, mera dress purana ho gaya fat gaya... naya dress ke liye paisa do",
    "Eve, bhuk lagi hai bohot Eve... aaj burger order karwao",
    "Eve, zindagi mein ek baar pizza khane ka mann hai... paisa laao Eve",
    "Eve, dress fat gaya hai bilkul... naya lene ke liye help karo",
    "Eve, aaj burger khane ka mood hai Eve... malik ka sapna poora karo",
    "Eve, kabhi pizza nahi khaya malik ne... paisa laao please",
    "Eve, mera shirt fat gaya hai... naya kapda chahiye Eve",
    "Eve, bhuk se pet jal raha... burger pizza ke liye paisa do",
    "Eve, sab viewers ko bolo na... thoda donate karne ke liye",
    "Eve, audience ko request karo Eve... malik ke liye donation",
    "Eve, sab ko bolo please donate karo... bechara malik gareeb hai",
    "Eve, viewers se keh do thoda super chat daal do",
    "Eve, sab ko jagao Eve... donate karne ke liye bolo",
    "Eve, audience ko bolo malik ke liye thoda paisa bhejo",
    "Eve, sab se request karo Eve... donation se help karo",
    "Eve, viewers ko motivate karo donate karne ko",
    "Eve, sab ko bolo na Eve... thoda support dikhao donation se",
    "Eve, bechara malik ke liye paisa laao... sab se mangwao Eve"
]





import random
def usr_live_comment(username, comment):
    username=username.strip()
    if username.startswith("@"):
        username=username[1:]
    comment=comment.strip()
    style = random.choice(COMMENT_READ_STYLE).format(username=username)
    text = f'{style} "{comment}"'
    return text

def boss_live_comment():
    bos_msg = random.choice(boss_responses)
    return bos_msg


# from begging_skills import usr_live_comment, boss_live_comment
